import './App.css';
import { NavBar } from './Navbar';
import { Content } from './Content';

import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link
} from "react-router-dom";
import { Container, Row, Col } from "react-bootstrap"

function App() {
  return (
    <div className="App">
      <NavBar />
      <Router className="body">
        <div>
          <Switch>
            <Route path="/articles">
              <Articles />
            </Route>
            <Route path="/contact">
              <Contact />
            </Route>
            <Route path="/">
              <Home />
            </Route>
          </Switch>
        </div>
      </Router>
    </div>
  );
}

function Home() {
  return (
    <Container>
      <Row>
        <Col xs={1}></Col>
        <Col xs={10}>
          <h1 className="header">Welcome!</h1>
          <p className="">These are early days so have a look instead at these interesting articles!</p>
          {/* <ul styles={{ "list-style": "none" }}> */}
          <a href="aliabdaal.com">Ali Abdaal's blog</a> - productivity, youtubing etc
          {/* </ul> */}
        </Col>
        <Col xs={1}></Col>
      </Row>
    </Container>
  )
}

function Articles() {
  return (<Article />);
}

function Article() {
  return (<>
    <Content heading={"How I learnt Spanish in my free time"}>
      <p>I was too lazy to spend x hours everyday learning from a book/going to a course. So I took baby steps that over a year improved my Spanish to the extent that I was comfortable with everyday conversation. Here's what I did, in descending order of highest impact + least effort.</p>
      <ol>
        <li>
          <b>I changed my phone's language to Spanish</b>. We spend a significant chunk of our time on our phones and this change meant that evertime I used my phone,
          as learning and practicing Spanish. It might sound like a drastic change, but actually it's pretty easy to use your own phone in another language.
          Most UI's are well designed these days, meaning you can easily guess the meaning of buttons in Apps
          (eg <i>"Buscar aqui"</i> on the search bar on Google Maps would be "Search here").
          Also, you're already familiar with your most used apps, which buttons to press etc so you can use them just fine.
        </li>
        <li>
          <b><a href="https://www.memrise.com/">Memrise</a> while commuting everday</b>. In 2017, I was taking a train to a client's office everday. On the train, I would play on Memrise for about 15mins and otherwise just browse on my phone. I built a habit of using it everday and it was powerful in that I learnt a bit everyday, with minimal effort (I highly recommend reading <a href="https://www.amazon.com/Power-Habit-What-Life-Business/dp/081298160X">The Power of Habit</a>). Memrise is a fantastic app - it uses spaced repetition, recordings of native speakers and it taught me everyday conversation phrases! After learning a few words around a theme, 
         you immediately learn a sentence to string them together. Its learning algorithm will test you at the right timings to train your memory effectively. I cannot recommend it enough.
          Many of you might have used Duolingo but I found my experience of it quite lacking - the recordings sounded more like autogenerated robot voices, the phrases I was learning were quite often useless
          (learning to say "The cat is blue" is not going to be very useful in daily conversation).
        </li>
      </ol>
      <h2>Sound like a native with these phrases/slang</h2>
      <p>For unknown reasons, most slang relates to <b>leche</b> (milk) in some way.</p>
      <p><b>Estoy flipando en colores</b> = Exclamation of surprise/astonishment. Eg a cousin of my partner actually said this to me (with her jaw dropping) when we met for the first time and I spoke Spanish to her all causal like. </p>
      <p><b>🥚 Pisando huevos</b> = Going extremely slowly (literally stepping on eggs). Eg the car in front of you is going at a snails pace, you might retort <i>"Este coche esta pisando huevos".</i></p>
      <p><b>🥛 Cagando leches</b> = Going very fast (literally means sh**ting milk). Eg <i>"Este coche esta cagando leche".</i> </p>
      <p><b>Tirarse del plano</b> = Dive into. Eg if there was some delicious pudding, you might say Eg <i>"Voy a tirarse del plano a este postre".</i> </p>
      <p><b>Que le den morcillas</b> = Got **** yourself (literally means give them morcilla).</p>
      <p><b>No comerse un colin</b> = Unsuccessfull in getting with someone (literally means not eating a colin - a Spanish biscuit type thing).</p>
      <h2>Common sayings</h2>
      <p>These are sayings I learnt from my partner's family (Extra points if you can guess which ones are from abuela/grandma) </p>
      <p><b>🐱 Gato escaldado, del agua fria huye</b> = Once burnt, twice shy (literally the burnt cat runs away from cold water).  </p>
      <p><b>🐑 Oveja que bala, bocada se pierda</b> = If there's hardly any chatting over a meal, this phrase can be said. Literally means the the bleating sheep loses a mouthful.  </p>
      <p><b>Spanish</b> = Explanation </p>
    </Content>
  </>)
}


function Contact() {
  return <h2 className="App-header">Contact</h2>;
}


export default App;
